"""CodexAdapter — autonome Code-Fixes (SecurityScanAgent + Refactoring).

Detection-Patterns:
- Branch `fix/security-findings` (1.0 — Standard-Branch SecurityScanAgent)
- Branch `fix/security-` Prefix (0.95)
- Branch `codex/` Prefix (0.9 — explizite Codex-Sessions)
- Body `Co-Authored-By: Codex` oder `## Security Fix` (0.9)
- Title `[Security]` Prefix oder `[Codex]` Prefix (0.85)

Merge-Policy: IMMER manual fuer Code-Fixes — Security-PRs muessen vom Menschen
verifiziert werden, Refactor-PRs koennen Side-Effects haben.
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional, Tuple

from .base import AgentAdapter, AgentDetection, MergeDecision


# Codex-Branch-Konventionen (vom SecurityScanAgent verwendet)
SECURITY_BRANCH_PREFIX = "fix/security-findings"
SECURITY_BRANCH_GENERIC = "fix/security-"
CODEX_BRANCH_PREFIX = "codex/"

# Body-Marker — vom SecurityScanAgent in PR-Body geschrieben
BODY_MARKERS = (
    "Co-Authored-By: Codex",
    "Co-Authored-By: SecurityScanAgent",
    "## Security Fix",
    "## 🔧 Security Fix",
    "Generated by SecurityScanAgent",
)


class CodexAdapter(AgentAdapter):
    """Codex/SecurityScanAgent PR-Detection + strikte Code-Review-Config."""

    agent_name = "codex"

    def detect(self, pr_payload: Dict[str, Any]) -> AgentDetection:
        """Codex/SecurityScanAgent PRs erkennen.

        Priorisiert nach Confidence:
        1. Branch `fix/security-findings` exakt (1.0 — kanonischer Branch)
        2. Branch `fix/security-` Prefix (0.95)
        3. Branch `codex/` (0.9)
        4. Body-Marker (0.9)
        5. Title `[Security]` oder `[Codex]` Prefix (0.85)
        """
        body = pr_payload.get("body") or ""
        title = pr_payload.get("title") or ""
        branch = (pr_payload.get("head") or {}).get("ref", "")

        if branch == SECURITY_BRANCH_PREFIX or branch.startswith(
            SECURITY_BRANCH_PREFIX + "-"
        ):
            return AgentDetection(
                matched=True, confidence=1.0, metadata={"src": "branch_security_canonical"},
            )
        if branch.startswith(SECURITY_BRANCH_GENERIC):
            return AgentDetection(
                matched=True, confidence=0.95, metadata={"src": "branch_security_generic"},
            )
        if branch.startswith(CODEX_BRANCH_PREFIX):
            return AgentDetection(
                matched=True, confidence=0.9, metadata={"src": "branch_codex"},
            )
        if any(marker in body for marker in BODY_MARKERS):
            return AgentDetection(
                matched=True, confidence=0.9, metadata={"src": "body_marker"},
            )
        if title.startswith("[Security]") or title.startswith("[Codex]"):
            return AgentDetection(
                matched=True, confidence=0.85, metadata={"src": "title_prefix"},
            )

        return AgentDetection(matched=False, confidence=0.0)

    def build_prompt(
        self,
        *,
        diff: str,
        pr_payload: Dict[str, Any],
        finding_context: Dict[str, Any],
        iteration: int,
        few_shot: List[Dict[str, Any]],
        knowledge: List[str],
        project: str,
    ) -> str:
        """Baut Codex-spezifischen Code-Review-Prompt."""
        from ..prompts.codex_prompt import build_codex_review_prompt
        return build_codex_review_prompt(
            diff=diff,
            project=project,
            iteration=iteration,
            files_changed=pr_payload.get("files_changed_paths") or [],
            knowledge=knowledge,
            few_shot=few_shot,
            finding_context=finding_context,
        )

    def model_preference(
        self, pr_payload: Dict[str, Any], diff_len: int,
    ) -> Tuple[str, str]:
        """Security-Fixes brauchen Tiefe — IMMER Opus primary, Sonnet als Fallback."""
        # Security-Fixes (Branch oder Title) → IMMER Opus
        branch = (pr_payload.get("head") or {}).get("ref", "")
        title = pr_payload.get("title") or ""
        if (
            branch.startswith(SECURITY_BRANCH_GENERIC)
            or branch == SECURITY_BRANCH_PREFIX
            or title.startswith("[Security]")
        ):
            return ("thinking", "standard")

        # Reine Refactorings: bei kleinem Diff Sonnet, sonst Opus
        if diff_len < 2000:
            return ("standard", "thinking")
        return ("thinking", "standard")

    def merge_policy(
        self,
        review: Dict[str, Any],
        pr_payload: Dict[str, Any],
        project: str,
    ) -> MergeDecision:
        """Code-Fixes brauchen IMMER manuelle Verifikation.

        Auch bei `approved` Verdict — der Mensch muss den Test laufen lassen
        und die Logik nachvollziehen. Auto-Merge ist hier zu riskant.
        """
        return MergeDecision.MANUAL

    def discord_channel(self, verdict: str) -> str:
        return "security-fixes"

    def iteration_mention(self) -> Optional[str]:
        """Codex-CLI laeuft als Subprocess vom SecurityScanAgent — kein Bot-Account.

        Bei Revisions ueberprueft der ScanAgent die Comments im naechsten Lauf
        und delegiert ggf. eine neue Codex-Session. Kein @mention noetig.
        """
        return None
